version: '3.8'
services:
  symfony-app-php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: symfony-app-php
    working_dir: /var/www/
    volumes:
      - "./:/var/www"
    networks:
      - symfony-app-network

  symfony-app-database:
    image: mysql:8.0
    container_name: symfony-app-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - symfony-app-network

  symfony-app-nginx:
    image: nginx:alpine
    container_name: symfony-app-nginx
    ports:
      - 8000:80
    volumes:
      - "./:/var/www"
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - symfony-app-network

networks:
  symfony-app-network:
    driver: bridge